name: Deploy Web Panel via GitHub Actions with Cloudflared

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout kode Anda
    - name: Checkout Code
      uses: actions/checkout@v3

    # Ubah direktori ke folder tempat `package.json` berada
    - name: Change directory to 'web'
      run: cd web

    # Instal dependensi
    - name: Install Dependencies
      run: |
        npm install

    # Jalankan server web
    - name: Start Web Panel
      run: |
        npm run build
        npm run start &

    # Instal Cloudflared
    - name: Install Cloudflared
      run: |
        sudo apt-get update && sudo apt-get install -y wget
        wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
        sudo mv cloudflared-linux-amd64 /usr/local/bin/cloudflared
        sudo chmod +x /usr/local/bin/cloudflared

    # Jalankan Cloudflared Tunnel
    - name: Start Cloudflared Tunnel
      run: |
        cloudflared tunnel --url http://localhost:3000 &
        sleep 5
        curl -s http://localhost:3000

    # Keep Action Alive
    - name: Keep Action Alive
      run: |
        while true; do echo "GitHub Action is running..."; sleep 60; done
